
language: php

sudo: false

php:
    - 7.0
    - 7.1

install:
    - composer update --prefer-source --no-interaction

script:
    - bin/phpunit --coverage-text -c build/phpunit-coverage.xml

notifications:
    email: false